# Generated by Django 4.2.7 on 2023-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=60)),
                ('desc', models.TextField(max_length=60)),
                ('tags', models.TextField(max_length=60)),
                ('cr', models.DateField()),
            ],
        ),
    ]
